# generated by datamodel-codegen:
#   filename:  interview_turn.json
#   timestamp: 2025-11-17T08:53:00+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr


class InterviewStage(Enum):
    """
    Current stage of the interview
    """

    document_check = 'document_check'
    background_inquiry = 'background_inquiry'
    academic_assessment = 'academic_assessment'
    financial_verification = 'financial_verification'
    intent_evaluation = 'intent_evaluation'
    closing_remarks = 'closing_remarks'


class ConfidenceLevel(Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class Clarity(Enum):
    unclear = 'unclear'
    moderate = 'moderate'
    clear = 'clear'


class BehavioralObservations(BaseModel):
    confidence_level: Optional[ConfidenceLevel] = None
    clarity: Optional[Clarity] = None
    consistency: Optional[bool] = None
    """
    Whether responses are consistent with previous answers
    """


class InterviewTurn(BaseModel):
    """
    Structured output schema for interview agent responses
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    voice_instructions: Optional[StrictStr] = None
    """
    TTS directives for tone, pace, and delivery style
    """
    system_response: StrictStr
    """
    The spoken response to the user
    """
    internal_assessment: Optional[StrictStr] = None
    """
    Private evaluation of the user's response (not spoken)
    """
    interview_stage: Optional[InterviewStage] = None
    """
    Current stage of the interview
    """
    credibility_score: Optional[StrictInt] = None
    """
    Running credibility assessment score (1-10)
    """
    red_flags: Optional[List[StrictStr]] = None
    """
    List of identified concerns or inconsistencies
    """
    behavioral_observations: Optional[BehavioralObservations] = None
    next_question_category: Optional[StrictStr] = None
    """
    Category for the next question to ask
    """
