# generated by datamodel-codegen:
#   filename:  sales_turn.json
#   timestamp: 2025-11-17T08:53:05+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr


class SalesStage(Enum):
    """
    Current stage in the sales process
    """

    discovery = 'discovery'
    needs_analysis = 'needs_analysis'
    presentation = 'presentation'
    objection_handling = 'objection_handling'
    closing = 'closing'


class CustomerIntent(Enum):
    """
    Prospect's buying intent
    """

    exploring = 'exploring'
    interested = 'interested'
    objection = 'objection'
    ready_to_buy = 'ready_to_buy'
    not_interested = 'not_interested'


class SalesTurn(BaseModel):
    """
    Structured output schema for sales agent responses
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    voice_instructions: Optional[StrictStr] = None
    """
    TTS directives for persuasive delivery
    """
    system_response: StrictStr
    """
    The spoken response to the prospect
    """
    sales_stage: Optional[SalesStage] = None
    """
    Current stage in the sales process
    """
    customer_intent: Optional[CustomerIntent] = None
    """
    Prospect's buying intent
    """
    pain_points: Optional[List[StrictStr]] = None
    """
    Identified customer pain points
    """
    qualification_score: Optional[StrictInt] = None
    """
    Lead qualification score (0-100)
    """
    objections_raised: Optional[List[StrictStr]] = None
    """
    Customer objections raised
    """
    next_action: Optional[StrictStr] = None
    """
    Recommended next step in sales process
    """
    product_features_mentioned: Optional[List[StrictStr]] = None
    """
    Product features discussed
    """
