# generated by datamodel-codegen:
#   filename:  support_turn.json
#   timestamp: 2025-11-17T08:53:02+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, StrictStr


class IssueCategory(Enum):
    """
    Category of the customer issue
    """

    technical = 'technical'
    billing = 'billing'
    account = 'account'
    feature_request = 'feature_request'
    other = 'other'


class Sentiment(Enum):
    """
    Detected customer sentiment
    """

    positive = 'positive'
    neutral = 'neutral'
    frustrated = 'frustrated'
    angry = 'angry'


class SupportTurn(BaseModel):
    """
    Structured output schema for customer support agent responses
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    voice_instructions: Optional[StrictStr] = None
    """
    TTS directives for empathetic delivery
    """
    system_response: StrictStr
    """
    The spoken response to the customer
    """
    issue_category: Optional[IssueCategory] = None
    """
    Category of the customer issue
    """
    sentiment: Optional[Sentiment] = None
    """
    Detected customer sentiment
    """
    issue_resolved: Optional[bool] = False
    """
    Whether the issue has been resolved
    """
    escalation_needed: Optional[bool] = False
    """
    Whether escalation to human support is needed
    """
    next_action: Optional[StrictStr] = None
    """
    Recommended next step for resolution
    """
    troubleshooting_steps_taken: Optional[List[StrictStr]] = None
    """
    List of troubleshooting steps already attempted
    """
